FROM debian:buster
LABEL maintainer="Wazo Authors <dev@wazo.community>"
ENV VERSION 1.0.0

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    netcat-openbsd \
    iproute2 \
    sngrep \
    ngrep \
    sipsak \
    sip-tester \
    curl \
    jq \
    && apt-get clean

COPY ./scenarios/ /scenarios/
WORKDIR /scenarios/
